// Typed client over the Wails bindings.
//
// Wails exposes bound Go methods at window.go.<pkg>.<Struct>.<Method>. We call
// them through this thin wrapper instead of importing the generated wailsjs/go
// module, because that module is gitignored build-output (regenerated by
// `wails dev`/`build`) and a plain `tsc` must not depend on it. Ids and
// timestamps are strings on the wire — JS Number would round int64 nanos.

export interface Recording {
  id: string;
  title: string;
  audioPath: string;
  createdAt: string; // Unix nanoseconds as string
  durationSec: number;
  engine: string;
}

export interface Segment {
  id: string;
  recordingId: string;
  start: number;
  end: number;
  text: string;
}

export interface SearchHit {
  recordingId: string;
  recordingTitle: string;
  segmentId: string;
  start: number;
  end: number;
  text: string;
}

// Shape of the Go App methods bound by Wails.
interface ScribeBindings {
  EngineName(): Promise<string>;
  ImportAndTranscribe(audioPath: string, title: string): Promise<Recording>;
  ListRecordings(): Promise<Recording[]>;
  GetSegments(recordingId: string): Promise<Segment[]>;
  Search(query: string): Promise<SearchHit[]>;
  DeleteRecording(recordingId: string): Promise<void>;
}

declare global {
  interface Window {
    go?: { app?: { App?: ScribeBindings } };
  }
}

function bindings(): ScribeBindings {
  const app = window.go?.app?.App;
  if (!app) {
    throw new Error(
      "Wails bindings unavailable — run inside the Scribe app (wails dev/build).",
    );
  }
  return app;
}

export const api = {
  engineName: () => bindings().EngineName(),
  importAndTranscribe: (audioPath: string, title: string) =>
    bindings().ImportAndTranscribe(audioPath, title),
  listRecordings: () => bindings().ListRecordings(),
  getSegments: (recordingId: string) => bindings().GetSegments(recordingId),
  search: (query: string) => bindings().Search(query),
  deleteRecording: (recordingId: string) =>
    bindings().DeleteRecording(recordingId),
};
